name: Build and deploy release docs

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy-release:
    name: Build and deploy release documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - name: Build release docs
        run: |
          uv run -- build_docs.py ${{ github.ref_name }}
          cd docs/build
          ln -s ${{ github.ref_name }} latest
      - name: Deploy release docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: release ${{ github.ref_name }}
          keep_files: true
